INSERT INTO TBL_FORNECEDOR (NAME, CATEGORY , ACTIVE, CONTACT) VALUES ('Maria Silva', 'Nacional', 'TRUE', '100000');
INSERT INTO TBL_FORNECEDOR (NAME, CATEGORY , ACTIVE, CONTACT) VALUES ('José Nunes', 'Internacional', 'FALSE', '2000000');
